version: '3.8'
services:
    
    # Application
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"
    # Web Server
    web:
        container_name: web
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80
    # Database
    database:
        container_name: database
        env_file:
            - .env
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33061:3306
volumes:
    dbdata: